### ISSUE TITLE
[Question] Are there any plans to update this mod to show information for more machines?

### ISSUE THREAD

**Issue by MrKono** [KeQingsocute520/GTTopAddition#1]
Do you have any plans to update the mod to show information for a wider range of machines? This mod is really remarkable, but I think it has the potential to display information for even more machines.

For example:
Temperature for AlloyBlastSmelter and MegaBlastFurnace in gcym
Capacity and Average IO for PSS

If you have no such plans, would it be permissible for me to create and release an addon that implements these features?

**Comment by MeowmelMuku** [comment]
我会在下个版本完成他的，不用你操心了，谢谢！
